In [1]:
import pandas as pd

In [2]:
df = pd.read_json("C:/Users/valde/Documents/GitHub/Wino-UROP/train_xl.jsonl", lines=True)
df

,qID,sentence,option1,option2,answer
0,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-2,Ian volunteered to eat Dennis's menudo after a...,Ian,Dennis,2
1,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-1,Ian volunteered to eat Dennis's menudo after a...,Ian,Dennis,1
2,3XWUWJ18TLO2DDRXF83QWLKRJ29UU4-1,"He never comes to my home, but I always go to ...",home,house,1
3,3XWUWJ18TLO2DDRXF83QWLKRJ29UU4-2,"He never comes to my home, but I always go to ...",home,house,2
4,3D5G8J4N5CI2K40F4RZLF9OG2CKVTH-2,"Kyle doesn't wear leg warmers to bed, while Lo...",Kyle,Logan,2
...,...,...,...,...,...
40393,3PKJ68EHDNUOUBAJ3ASD64MQ8GSJHJ-1,I felt lucky because when the fish slipped of ...,pole,net,1
40394,3W1K7D6QSDVJX2B852X30LVRM6WZBL-1,Dennis took months to write back to Kenneth's ...,Dennis,Kenneth,1
40395,3W1K7D6QSDVJX2B852X30LVRM6WZBL-2,Dennis took months to write back to Kenneth's ...,Dennis,Kenneth,2
40396,3BO3NEOQM2VSJ2H6ZK9L5F8V75BAIT-1,My hair looked better in a braid than a ponyta...,braid,ponytail,1
40397,3BO3NEOQM2VSJ2H6ZK9L5F8V75BAIT-2,My hair looked better in a braid than a ponyta...,braid,ponytail,2

In [3]:
# Liste des mots Ã  rechercher
mots = ['empty', 'full', 'box', 'bag', 'bowl', 'bottle', 'cup', 'pan', 'pot']

# Fonction pour vÃ©rifier si une ligne contient au moins un des mots
def contient_mots(row, mots):
    return any(mot in row['sentence'] or mot in row['option1'] or mot in row['option2'] for mot in mots)

# Filtrer les lignes
df_filtre = df[df.apply(contient_mots, axis=1, mots=mots)]

# Afficher le DataFrame filtrÃ©
df_filtre

,qID,sentence,option1,option2,answer
0,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-2,Ian volunteered to eat Dennis's menudo after a...,Ian,Dennis,2
1,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-1,Ian volunteered to eat Dennis's menudo after a...,Ian,Dennis,1
10,304QEQWKZRY6EBUR5DPX06S39IH0OJ-2,The treasury workers took the gold bars off of...,safe,trolley,2
11,304QEQWKZRY6EBUR5DPX06S39IH0OJ-1,The treasury workers took the gold bars off of...,safe,trolley,1
20,3NRZ1LDP7W4677DB493437C7D3WZP2-2,I picked up a bag of peanuts and raisins for a...,raisins,peanuts,2
...,...,...,...,...,...
40371,38EHZ67RIO6FPCK06ZZNTUQFM97GMQ-1,I took the food out of the oven and placed it ...,oven,bowl,1
40378,38F60IALAIVMR3ZZ1UBWUGYR9PYT0Z-2,The scale got broken when the bag of sugar was...,scale,bag,2
40379,38F60IALAIVMR3ZZ1UBWUGYR9PYT0Z-1,The scale got broken when the bag of sugar was...,scale,bag,1
40384,3QREJ3J435B0LGYYWEJNR93JUNCKLE-2,She prefers to use ceramic over plastic cups f...,ceramic,plastic,2
40385,3QREJ3J435B0LGYYWEJNR93JUNCKLE-1,She prefers to use ceramic over plastic cups f...,ceramic,plastic,1