In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("phrases_annotees.csv")
pd.set_option('display.max_colwidth', None)

In [3]:
df = df[df['label'] != -1]

In [4]:
df

,qID,phrase,option1,option2,answer,label
0,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-1,Ian volunteered to eat Dennis's menudo after already having a bowl because _ enjoyed eating intestine.,Ian,Dennis,1,0
1,3NRZ1LDP7W4677DB493437C7D3WZP2-1,I picked up a bag of peanuts and raisins for a snack. I wanted a sweeter snack out so I ate the _ for now.,raisins,peanuts,1,0
7,3MZ3TAMYTLL5OU4GHXJ7879WIBGRIT-1,Ben had to either stop eating chocolates or nuts. He chose to stop eating the _ because they were sweet.,chocolates,nuts,1,1
9,3PIOQ99R7YKPIN7OI7R4IQSX6RPUNM-1,"William wanted an egg for breakfast, but Kevin ate the last one, so _ had to eat cereal.",William,Kevin,1,0
10,30Y6N4AHYPUOGJOUPJIWHATJQ9LDRW-1,Since _ arrived at work sooner Dennis would eat their lunch before Adam in the break room at their job.,Dennis,Adam,1,0
...,...,...,...,...,...,...
1719,329E6HTMSYGJ5C89Q8FNVN92U0L3KH-1,Jean really liked the profiteroles but not the peas because the _ were very sweet.,profiteroles,peas,1,0
1721,3YCT0L9OMONOXZERD084VNYHEQ4SN8-1,Katrina had an obsession with donuts and cake but not Sarah so _ was a heavy weight.,Katrina,Sarah,1,1
1723,3SSN80MU8E2VLAFNAXMB23Y5ZM5KXV-1,William loved having fresh eggs for breakfast every morning but Brett hated eggs. _ bought a chicken to raise for eggs.,William,Brett,1,0
1725,3V0TR1NRVCGYBVIREV7HBEYB1IDA44-1,"While making her breakfast, Sam sweetened her oatmeal with honey. The _ was sweet and sticky.",honey,oatmeal,1,0
1731,3ZCC2DXSD720BVV7ZAX42RWHBK8YYT-1,"Adam placed the fruit into the bag instead of the box, as the fruit fit well into the _ .",bag,box,1,0