In [1]:
import pandas as pd
import string

In [2]:
df = pd.read_json("C:/Users/valde/Documents/GitHub/Wino-UROP/lemma_train_xl.jsonl", lines=True)
df

,qID,groupID,sentence,option1,lemma_option1,option2,lemma_option2,answer,tokens_sentence,lemma_sentence,POS_sentence,common_tokens,lemma_common_tokens,special_alternate,lemma_special_alternate
0,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-2,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE,Ian volunteered to eat Dennis's menudo after a...,Ian,Ian,Dennis,Dennis,2,"[Ian, volunteered, to, eat, Dennis, 's, menudo...","[Ian, volunteer, to, eat, Dennis, 's, menudo, ...","[PROPN, VERB, PART, VERB, PROPN, PART, NOUN, A...","[Ian, volunteered, to, eat, Dennis, 's, menudo...","[Ian, volunteer, to, eat, Dennis, 's, menudo, ...",[despised],[despise]
1,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-1,3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE,Ian volunteered to eat Dennis's menudo after a...,Ian,Ian,Dennis,Dennis,1,"[Ian, volunteered, to, eat, Dennis, 's, menudo...","[Ian, volunteer, to, eat, Dennis, 's, menudo, ...","[PROPN, VERB, PART, VERB, PROPN, PART, NOUN, A...","[Ian, volunteered, to, eat, Dennis, 's, menudo...","[Ian, volunteer, to, eat, Dennis, 's, menudo, ...",[enjoyed],[enjoy]
2,3XWUWJ18TLO2DDRXF83QWLKRJ29UU4-1,3XWUWJ18TLO2DDRXF83QWLKRJ29UU4,"He never comes to my home, but I always go to ...",home,home,house,house,1,"[He, never, comes, to, my, home, ,, but, I, al...","[he, never, come, to, my, home, ,, but, I, alw...","[PRON, ADV, VERB, ADP, PRON, NOUN, PUNCT, CCON...","[He, never, comes, to, my, home, ,, but, I, al...","[he, never, come, to, my, home, ,, but, I, alw...",[smaller],[small]
3,3XWUWJ18TLO2DDRXF83QWLKRJ29UU4-2,3XWUWJ18TLO2DDRXF83QWLKRJ29UU4,"He never comes to my home, but I always go to ...",home,home,house,house,2,"[He, never, comes, to, my, home, ,, but, I, al...","[he, never, come, to, my, home, ,, but, I, alw...","[PRON, ADV, VERB, ADP, PRON, NOUN, PUNCT, CCON...","[He, never, comes, to, my, home, ,, but, I, al...","[he, never, come, to, my, home, ,, but, I, alw...",[bigger],[big]
4,3D5G8J4N5CI2K40F4RZLF9OG2CKVTH-2,3D5G8J4N5CI2K40F4RZLF9OG2CKVTH,"Kyle doesn't wear leg warmers to bed, while Lo...",Kyle,kyle,Logan,Logan,2,"[Kyle, does, n't, wear, leg, warmers, to, bed,...","[Kyle, do, not, wear, leg, warmer, to, bed, ,,...","[PROPN, AUX, PART, VERB, NOUN, NOUN, ADP, NOUN...","[Kyle, does, n't, wear, leg, warmers, to, bed,...","[Kyle, do, not, wear, leg, warmer, to, bed, ,,...",[colder],[colder]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40393,3PKJ68EHDNUOUBAJ3ASD64MQ8GSJHJ-1,3PKJ68EHDNUOUBAJ3ASD64MQ8GSJHJ,I felt lucky because when the fish slipped of ...,pole,pole,net,net,1,"[I, felt, lucky, because, when, the, fish, sli...","[I, feel, lucky, because, when, the, fish, sli...","[PRON, VERB, ADJ, SCONJ, SCONJ, DET, NOUN, VER...","[I, felt, lucky, because, when, the, fish, sli...","[I, feel, lucky, because, when, the, fish, sli...","[at, first]","[at, first]"
40394,3W1K7D6QSDVJX2B852X30LVRM6WZBL-1,3W1K7D6QSDVJX2B852X30LVRM6WZBL,Dennis took months to write back to Kenneth's ...,Dennis,Dennis,Kenneth,Kenneth,1,"[Dennis, took, months, to, write, back, to, Ke...","[Dennis, take, month, to, write, back, to, Ken...","[PROPN, VERB, NOUN, PART, VERB, ADV, ADP, PROP...","[Dennis, took, months, to, write, back, to, Ke...","[Dennis, take, month, to, write, back, to, Ken...",[inconsiderate],[inconsiderate]
40395,3W1K7D6QSDVJX2B852X30LVRM6WZBL-2,3W1K7D6QSDVJX2B852X30LVRM6WZBL,Dennis took months to write back to Kenneth's ...,Dennis,Dennis,Kenneth,Kenneth,2,"[Dennis, took, months, to, write, back, to, Ke...","[Dennis, take, month, to, write, back, to, Ken...","[PROPN, VERB, NOUN, PART, VERB, ADV, ADP, PROP...","[Dennis, took, months, to, write, back, to, Ke...","[Dennis, take, month, to, write, back, to, Ken...",[hurt],[hurt]
40396,3BO3NEOQM2VSJ2H6ZK9L5F8V75BAIT-1,3BO3NEOQM2VSJ2H6ZK9L5F8V75BAIT,My hair looked better in a braid than a ponyta...,braid,braid,ponytail,ponytail,1,"[My, hair, looked, better, in, a, braid, than,...","[my, hair, look, well, in, a, braid, than, a, ...","[PRON, NOUN, VERB, ADV, ADP, DET, NOUN, ADP, D...","[My, hair, looked, better, in, a, braid, than,...","[my, hair, look, well, in, a, braid, than, a, ...",[so],[so]
40397,3BO3NEOQM2VSJ2H6ZK9L5F8V75BAIT-2,3BO3NEOQM2VSJ2H6ZK9L5F8V75BAIT,My hair looked better in a braid than a ponyta...,braid,braid,ponytail,ponytail,2,"[My, hair, looked, better, in, a, braid, than,...","[my, hair, look, well, in, a, braid, than, a, ...","[PRON, NOUN, VERB, ADV, ADP, DET, NOUN, ADP, D...","[My, hair, looked, better, in, a, braid, than,...","[my, hair, look, well, in, a, braid, than, a, ...","[but, anyway]","[but, anyway]"

### filtrage df

In [3]:
# Supprimer les lignes où la colonne "answer" contient la valeur "2"
df = df[df['answer'] != 2]

# Sélectionner les colonnes "lemma_option1" et "lemma_option2"
df = df[['lemma_option1', 'lemma_option2']]
df

      lemma_option1 lemma_option2
1               Ian        Dennis
2              home         house
5              kyle         Logan
7               gps           map
9             emily      Patricia
...             ...           ...
40389         Craig      Benjamin
40391      Victoria         Elena
40393          pole           net
40394        Dennis       Kenneth
40396         braid      ponytail

[20199 rows x 2 columns]

In [4]:
edge_counts = df.groupby(['lemma_option1', 'lemma_option2']).size().reset_index(name='Weight')
edge_counts = edge_counts.sort_values(by='Weight', ascending=False)
edge_counts.columns = ['Source', 'Target', 'Weight']
edge_counts.to_csv('edges.csv', index=False)
display(edge_counts)

         Source    Target  Weight
2937        car     truck      21
4121       erin     kayla      17
700     Jessica  Jennifer      17
254      Carrie  Samantha      16
1101      Maria     megan      16
...         ...       ...     ...
4238      field       net       1
4236      field      hole       1
4234      field    garden       1
4233      field   gallery       1
8891  zucchinis    potato       1

[8892 rows x 3 columns]

In [5]:
df = edge_counts

# Step 1: Extract unique nodes
unique_nodes = pd.unique(df[['Source', 'Target']].values.ravel('K'))

# Step 2: Initialize the adjacency matrix
adj_matrix = pd.DataFrame(0, index=unique_nodes, columns=unique_nodes)

# Step 3: Populate the adjacency matrix
for _, row in df.iterrows():
    adj_matrix.at[row['Source'], row['Target']] = row['Weight']

# Display the adjacency matrix
print(adj_matrix)

           car  erin  Jessica  Carrie  Maria  Laura  Betty  Lindsey  kayla  \
car          0     0        0       0      0      0      0        0      0
erin         0     0       11       3      5     11      8        6     17
Jessica      0    12        0       8      7      7      4        3      8
Carrie       0     6        7       0      8      8      5        7      3
Maria        0     4        5       4      0      8      5        8     10
...        ...   ...      ...     ...    ...    ...    ...      ...    ...
Nail         0     0        0       0      0      0      0        0      0
drive        0     0        0       0      0      0      0        0      0
cursor       0     0        0       0      0      0      0        0      0
landscape    0     0        0       0      0      0      0        0      0
spar         0     0        0       0      0      0      0        0      0

           Angela  ...  plaque  paramedic  frond  firewood  thought  Nail  \
car             0  ...       0          0      0         0        0     0
erin           10  ...       0          0      0         0        0     0
Jessica         7  ...       0          0      0         0        0     0
Carrie         11  ...       0          0      0         0        0     0
Maria           9  ...       0          0      0         0        0     0
...           ...  ...     ...        ...    ...       ...      ...   ...
Nail            0  ...       0          0      0         0        0     0
drive           0  ...       0          0      0         0        0     0
cursor          0  ...       0          0      0         0        0     0
landscape       0  ...       0          0      0         0        0     0
spar            0  ...       0          0      0         0        0     0

           drive  cursor  landscape  spar
car            0       0          0     0
erin           0       0          0     0
Jessica        0       0          0     0
Carrie         0       0          0     0
Maria          0       0          0     0
...          ...     ...        ...   ...
Nail           0       0          0     0
drive          0       0          0     0
cursor         0       0          0     0
landscape      0       0          0     0
spar           0       0          0     0

[3426 rows x 3426 columns]

In [6]:
edge_counts

         Source    Target  Weight
2937        car     truck      21
4121       erin     kayla      17
700     Jessica  Jennifer      17
254      Carrie  Samantha      16
1101      Maria     megan      16
...         ...       ...     ...
4238      field       net       1
4236      field      hole       1
4234      field    garden       1
4233      field   gallery       1
8891  zucchinis    potato       1

[8892 rows x 3 columns]

In [7]:
# Enregistrer le DataFrame au format CSV
edge_counts.to_csv('edges_option.csv', index=False)